-- ============================================================
-- IndusTaskManagement SCHEMA script (generated by SMO)
-- Run this against your TARGET database (e.g. IndusOrbit).
-- Creates schemas + tables + keys + indexes + SPs (NO data).
-- ============================================================
SET NOCOUNT ON;
GO
IF SCHEMA_ID('app') IS NULL EXEC('CREATE SCHEMA [app]');
GO
/****** Cannot script Unresolved Entities : Server[@Name='DESKTOP-L96U5S2\MSSQLSERVER03']/Database[@Name='IndusTaskManagement']/UnresolvedEntity[@Name='inserted'] ******/
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[app].[OnsiteVisits]') AND type in (N'U'))
BEGIN
CREATE TABLE [app].[OnsiteVisits](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[ClientCode] [nvarchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[Person] [nvarchar](120) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[FromDate] [nvarchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ToDate] [nvarchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Days] [nvarchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Status] [nvarchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[Age] [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[MobileNo] [nvarchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Location] [nvarchar](200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[TicketCharge] [nvarchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[HotelCharge] [nvarchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[FoodCharge] [nvarchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SiteCharge] [nvarchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Emailed] [bit] NOT NULL,
	[IsDeletedTransaction] [bit] NOT NULL,
	[CreatedDate] [datetime2](7) NULL,
	[CreatedBy] [int] NULL,
	[ModifiedDate] [datetime2](7) NULL,
	[ModifiedBy] [int] NULL,
	[DeletedDate] [datetime2](7) NULL,
	[DeletedBy] [int] NULL,
 CONSTRAINT [PK_app_OnsiteVisits] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
END
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[app].[OnboardingInbox]') AND type in (N'U'))
BEGIN
CREATE TABLE [app].[OnboardingInbox](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[ClientCode] [nvarchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[PayloadJson] [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[Source] [nvarchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[ReceivedAt] [datetime2](7) NOT NULL,
	[IsLoaded] [bit] NOT NULL,
 CONSTRAINT [PK_app_OnboardingInbox] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
END
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[Notifications]') AND type in (N'U'))
BEGIN
CREATE TABLE [dbo].[Notifications](
	[NotificationID] [int] IDENTITY(1,1) NOT NULL,
	[UserID_To] [int] NOT NULL,
	[MessageText] [nvarchar](500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[NavigateURL] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[IsRead] [bit] NOT NULL,
	[DateCreated] [datetime] NOT NULL,
 CONSTRAINT [PK_Notifications] PRIMARY KEY CLUSTERED 
(
	[NotificationID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
END
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[app].[Notifications]') AND type in (N'U'))
BEGIN
CREATE TABLE [app].[Notifications](
	[NotificationID] [bigint] IDENTITY(1,1) NOT NULL,
	[UserID] [bigint] NOT NULL,
	[CompanyID] [int] NOT NULL,
	[Type] [nvarchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[Title] [nvarchar](200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Body] [nvarchar](500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Link] [nvarchar](300) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[RefId] [nvarchar](100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[IconKey] [nvarchar](60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[IsRead] [bit] NOT NULL,
	[CreatedAt] [datetime2](7) NOT NULL,
 CONSTRAINT [PK_Notifications] PRIMARY KEY CLUSTERED 
(
	[NotificationID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
END
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[Modules]') AND type in (N'U'))
BEGIN
CREATE TABLE [dbo].[Modules](
	[ModuleName] [nvarchar](128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
END
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[app].[ModuleMaster]') AND type in (N'U'))
BEGIN
CREATE TABLE [app].[ModuleMaster](
	[ModuleID] [bigint] IDENTITY(1,1) NOT NULL,
	[ModuleName] [nvarchar](200) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[ModuleDisplayName] [nvarchar](120) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[ModuleHeadName] [nvarchar](100) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[ModuleHeadDisplayName] [nvarchar](100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ModuleDisplayOrder] [real] NOT NULL,
	[SetGroupIndex] [real] NOT NULL,
	[ModuleIcon] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ParentModuleName] [nvarchar](200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ReactRoutePath] [nvarchar](200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CompanyID] [int] NOT NULL,
	[IsDeletedTransaction] [bit] NOT NULL,
	[IsSidebarItem] [bit] NOT NULL,
 CONSTRAINT [PK_app_ModuleMaster] PRIMARY KEY CLUSTERED 
(
	[ModuleID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
END
GO
SET ANSI_PADDING OFF
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[app].[ModuleGroupDeletionLog]') AND type in (N'U'))
BEGIN
CREATE TABLE [app].[ModuleGroupDeletionLog](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[ApplicationName] [nvarchar](100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ModuleGroupName] [nvarchar](200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ModulesDeleted] [int] NOT NULL,
	[Reason] [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DeletedByUserId] [bigint] NULL,
	[DeletedByName] [nvarchar](200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DeletedByEmail] [nvarchar](256) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DeletedAt] [datetime2](0) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
END
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[app].[Milestones]') AND type in (N'U'))
BEGIN
CREATE TABLE [app].[Milestones](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[ClientCode] [nvarchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[Name] [nvarchar](120) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[PlannedDate] [nvarchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ActualDate] [nvarchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ResPerson] [nvarchar](120) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Status] [nvarchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[SortOrder] [int] NOT NULL,
	[MilestoneGroup] [nvarchar](60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[TaskTimeline] [nvarchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[EndDate] [nvarchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[StartDateVariance] [nvarchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ScheduledStartStatus] [nvarchar](40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[RemarkStartDelay] [nvarchar](300) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[TimelineVariance] [nvarchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[TimelineVarianceStatus] [nvarchar](40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[RemarkDuration] [nvarchar](300) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Emailed] [bit] NOT NULL,
	[Tasked] [bit] NOT NULL,
	[IsDeletedTransaction] [bit] NOT NULL,
	[CreatedDate] [datetime2](7) NULL,
	[CreatedBy] [int] NULL,
	[ModifiedDate] [datetime2](7) NULL,
	[ModifiedBy] [int] NULL,
	[DeletedDate] [datetime2](7) NULL,
	[DeletedBy] [int] NULL,
 CONSTRAINT [PK_app_Milestones] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
END
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[app].[Employees]') AND type in (N'U'))
BEGIN
CREATE TABLE [app].[Employees](
	[EmployeeID] [int] IDENTITY(1,1) NOT NULL,
	[FullName] [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[Email] [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[PasswordHash] [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[PhoneNumber] [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PersonalEmail] [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DateOfBirth] [datetime2](7) NULL,
	[Gender] [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[BloodGroup] [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[MaritalStatus] [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[WeddingDate] [datetime2](7) NULL,
	[CurrentAddress] [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PermanentAddress] [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DateOfJoining] [datetime2](7) NOT NULL,
	[ConfirmationDate] [datetime2](7) NULL,
	[EmployeeType] [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[WorkLocation] [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[UanNumber] [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PanCardNumber] [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[AadharCardNumber] [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[IsActive] [bit] NOT NULL,
	[Status] [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[IsLoginEnabled] [bit] NOT NULL,
	[PhotoPath] [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CreatedAt] [datetime2](7) NOT NULL,
	[UpdatedAt] [datetime2](7) NULL,
	[RoleID] [int] NOT NULL,
	[DepartmentID] [int] NOT NULL,
	[DesignationID] [int] NULL,
	[ReportingManagerID] [int] NULL,
	[FatherName] [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[EmergencyContactNumber] [nvarchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[EmergencyContactRelation] [nvarchar](100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CanProcureAssets] [bit] NOT NULL,
	[EmployeeCode] [nvarchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[BiometricCode] [nvarchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
 CONSTRAINT [PK_app_Employees] PRIMARY KEY CLUSTERED 
(
	[EmployeeID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
END
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[app].[EmailTemplates]') AND type in (N'U'))
BEGIN
CREATE TABLE [app].[EmailTemplates](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Name] [nvarchar](200) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[Subject] [nvarchar](400) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[Body] [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[Category] [nvarchar](80) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[IsActive] [bit] NOT NULL,
	[CreatedAt] [datetime2](7) NOT NULL,
	[UpdatedAt] [datetime2](7) NOT NULL,
	[IsDeletedTransaction] [bit] NOT NULL,
	[CreatedDate] [datetime2](7) NULL,
	[CreatedBy] [int] NULL,
	[ModifiedDate] [datetime2](7) NULL,
	[ModifiedBy] [int] NULL,
	[DeletedDate] [datetime2](7) NULL,
	[DeletedBy] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
END
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[app].[EmailTemplateAttachments]') AND type in (N'U'))
BEGIN
CREATE TABLE [app].[EmailTemplateAttachments](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[TemplateId] [int] NOT NULL,
	[Filename] [nvarchar](300) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[ContentType] [nvarchar](200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Content] [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[Size] [bigint] NULL,
	[CreatedAt] [datetime2](7) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
END
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[app].[EmailHistory]') AND type in (N'U'))
BEGIN
CREATE TABLE [app].[EmailHistory](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Recipients] [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ToJson] [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CcJson] [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[BccJson] [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Subject] [nvarchar](500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[BodyHtml] [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[BodyText] [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[AttachmentsJson] [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ClientCode] [nvarchar](60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ClientName] [nvarchar](300) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PointId] [int] NULL,
	[TicketId] [int] NULL,
	[Module] [nvarchar](100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Provider] [nvarchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Status] [nvarchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ErrorMessage] [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SentByEmail] [nvarchar](200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SentByName] [nvarchar](200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SentAt] [datetime] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
END
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[Customers]') AND type in (N'U'))
BEGIN
CREATE TABLE [dbo].[Customers](
	[CustomerID] [int] IDENTITY(1,1) NOT NULL,
	[CustomerName] [nvarchar](150) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[CompanyName] [nvarchar](150) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[ContactPerson] [nvarchar](100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ContactEmail] [nvarchar](100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ContactPhone] [nvarchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[IsActive] [bit] NOT NULL,
	[DateCreated] [datetime] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[CustomerID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
END
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[app].[Clients]') AND type in (N'U'))
BEGIN
CREATE TABLE [app].[Clients](
	[ClientCode] [nvarchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[Name] [nvarchar](150) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[City] [nvarchar](80) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Gstin] [nvarchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Contact] [nvarchar](120) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Email] [nvarchar](150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Mobile] [nvarchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Segment] [nvarchar](80) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Application] [nvarchar](40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Product] [nvarchar](60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Consultant] [nvarchar](120) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ConsultantUserId] [int] NULL,
	[Status] [nvarchar](40) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[Progress] [int] NOT NULL,
	[CompanyLogin] [nvarchar](80) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PasswordMasked] [nvarchar](80) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[UserLogin] [nvarchar](80) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Url] [nvarchar](300) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[KickoffDone] [bit] NOT NULL,
	[KickoffDate] [nvarchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[MastersSent] [bit] NOT NULL,
	[SignoffDone] [bit] NOT NULL,
	[Source] [nvarchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CreatedAt] [datetime2](7) NOT NULL,
	[CreatedDate] [datetime2](7) NULL,
	[CreatedBy] [int] NULL,
	[ModifiedDate] [datetime2](7) NULL,
	[ModifiedBy] [int] NULL,
	[DeletedDate] [datetime2](7) NULL,
	[DeletedBy] [int] NULL,
 CONSTRAINT [PK_app_Clients] PRIMARY KEY CLUSTERED 
(
	[ClientCode] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
END
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[app].[ClientModules]') AND type in (N'U'))
BEGIN
CREATE TABLE [app].[ClientModules](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[ClientCode] [nvarchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[ModuleName] [nvarchar](80) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[IsOn] [bit] NOT NULL,
 CONSTRAINT [PK_app_ClientModules] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
END
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[app].[ClientDocuments]') AND type in (N'U'))
BEGIN
CREATE TABLE [app].[ClientDocuments](
	[DocId] [int] IDENTITY(1,1) NOT NULL,
	[ClientCode] [nvarchar](60) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[DocType] [nvarchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[HtmlContent] [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[SavedByUserId] [int] NULL,
	[SavedByName] [nvarchar](150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SavedAt] [datetime2](7) NOT NULL,
	[UpdatedAt] [datetime2](7) NULL,
	[CreatedDate] [datetime2](7) NULL,
	[CreatedBy] [int] NULL,
	[ModifiedDate] [datetime2](7) NULL,
	[ModifiedBy] [int] NULL,
	[DeletedDate] [datetime2](7) NULL,
	[DeletedBy] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[DocId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [UQ_ClientDocuments_Client_Type] UNIQUE NONCLUSTERED 
(
	[ClientCode] ASC,
	[DocType] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
END
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[app].[ChatRooms]') AND type in (N'U'))
BEGIN
CREATE TABLE [app].[ChatRooms](
	[RoomID] [bigint] IDENTITY(1,1) NOT NULL,
	[CompanyID] [int] NOT NULL,
	[Type] [nvarchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[Name] [nvarchar](200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Description] [nvarchar](1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[AvatarUrl] [nvarchar](500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[IsPublic] [bit] NOT NULL,
	[IsReadOnly] [bit] NOT NULL,
	[CreatedBy] [bigint] NOT NULL,
	[CreatedDate] [datetime2](7) NOT NULL,
	[UpdatedDate] [datetime2](7) NOT NULL,
	[LastMessageAt] [datetime2](7) NULL,
	[LastMessagePreview] [nvarchar](500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[LastMessageBy] [bigint] NULL,
	[IsArchived] [bit] NOT NULL,
	[IsDeleted] [bit] NOT NULL,
	[Participants] [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
PRIMARY KEY CLUSTERED 
(
	[RoomID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
END
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[app].[ChatMessageStars]') AND type in (N'U'))
BEGIN
CREATE TABLE [app].[ChatMessageStars](
	[UserID] [bigint] NOT NULL,
	[MessageID] [bigint] NOT NULL,
	[CompanyID] [int] NOT NULL,
	[StarredAt] [datetime2](7) NOT NULL,
 CONSTRAINT [PK_ChatMessageStars] PRIMARY KEY CLUSTERED 
(
	[UserID] ASC,
	[MessageID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
END
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[app].[ChatMessages]') AND type in (N'U'))
BEGIN
CREATE TABLE [app].[ChatMessages](
	[MessageID] [bigint] IDENTITY(1,1) NOT NULL,
	[RoomID] [bigint] NOT NULL,
	[CompanyID] [int] NOT NULL,
	[UserID] [bigint] NOT NULL,
	[Content] [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[MessageType] [nvarchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[ParentMessageID] [bigint] NULL,
	[ReplyDepth] [int] NOT NULL,
	[ReplyCount] [int] NOT NULL,
	[CreatedAt] [datetime2](7) NOT NULL,
	[EditedAt] [datetime2](7) NULL,
	[IsEdited] [bit] NOT NULL,
	[IsDeleted] [bit] NOT NULL,
	[Reactions] [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Attachments] [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[IsPinned] [bit] NOT NULL,
	[PinnedBy] [bigint] NULL,
	[PinnedAt] [datetime2](7) NULL,
PRIMARY KEY CLUSTERED 
(
	[MessageID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
END
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[app].[ChatMessageHidden]') AND type in (N'U'))
BEGIN
CREATE TABLE [app].[ChatMessageHidden](
	[UserID] [bigint] NOT NULL,
	[MessageID] [bigint] NOT NULL,
	[CompanyID] [int] NOT NULL,
	[HiddenAt] [datetime2](7) NOT NULL,
 CONSTRAINT [PK_ChatMessageHidden] PRIMARY KEY CLUSTERED 
(
	[UserID] ASC,
	[MessageID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
END
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[app].[ChangeRequests]') AND type in (N'U'))
BEGIN
CREATE TABLE [app].[ChangeRequests](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[ClientCode] [nvarchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[ModuleName] [nvarchar](120) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Description] [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[RaisedBy] [nvarchar](120) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[RaisedDate] [nvarchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[QueryType] [nvarchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[Status] [nvarchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[InBugTool] [bit] NOT NULL,
	[ReportedBy] [nvarchar](120) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CompletionDate] [nvarchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CompletionDays] [nvarchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Remark] [nvarchar](500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Emailed] [bit] NOT NULL,
	[Tasked] [bit] NOT NULL,
	[IsDeletedTransaction] [bit] NOT NULL,
	[Pointed] [bit] NOT NULL,
	[CreatedDate] [datetime2](7) NULL,
	[CreatedBy] [int] NULL,
	[ModifiedDate] [datetime2](7) NULL,
	[ModifiedBy] [int] NULL,
	[DeletedDate] [datetime2](7) NULL,
	[DeletedBy] [int] NULL,
	[SubModule] [nvarchar](200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PointID] [int] NULL,
 CONSTRAINT [PK_app_ChangeRequests] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
END
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[Categories]') AND type in (N'U'))
BEGIN
CREATE TABLE [dbo].[Categories](
	[CategoryID] [int] IDENTITY(1,1) NOT NULL,
	[CategoryName] [nvarchar](100) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[IsActive] [bit] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[CategoryID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
END
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[Products]') AND type in (N'U'))
BEGIN
CREATE TABLE [dbo].[Products](
	[ProductID] [int] IDENTITY(1,1) NOT NULL,
	[ProductName] [nvarchar](100) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[ProductVersion] [nvarchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[IsActive] [bit] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[ProductID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
UNIQUE NONCLUSTERED 
(
	[ProductName] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
END
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[app].[UserModuleAuthentication]') AND type in (N'U'))
BEGIN
CREATE TABLE [app].[UserModuleAuthentication](
	[UserModuleAuthenticationID] [bigint] IDENTITY(1,1) NOT NULL,
	[UserID] [bigint] NOT NULL,
	[ModuleID] [bigint] NOT NULL,
	[CanView] [bit] NOT NULL,
	[CanSave] [bit] NOT NULL,
	[CanEdit] [bit] NOT NULL,
	[CanDelete] [bit] NOT NULL,
	[CanPrint] [bit] NOT NULL,
	[CanExport] [bit] NOT NULL,
	[CanCancel] [bit] NOT NULL,
	[CompanyID] [int] NOT NULL,
	[IsDeletedTransaction] [bit] NOT NULL,
 CONSTRAINT [PK_app_UMA] PRIMARY KEY CLUSTERED 
(
	[UserModuleAuthenticationID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
END
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[app].[TrainingUpdates]') AND type in (N'U'))
BEGIN
CREATE TABLE [app].[TrainingUpdates](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[ClientCode] [nvarchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[ModuleName] [nvarchar](80) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SubModule] [nvarchar](120) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[LogDate] [nvarchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[StartTime] [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[EndTime] [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Trainee] [nvarchar](120) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Trainer] [nvarchar](120) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Status] [nvarchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[Details] [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[VideoUrl] [nvarchar](300) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Emailed] [bit] NOT NULL,
	[Tasked] [bit] NOT NULL,
	[TimelineDays] [nvarchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Remark] [nvarchar](500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[IsDeletedTransaction] [bit] NOT NULL,
	[CreatedDate] [datetime2](7) NULL,
	[CreatedBy] [int] NULL,
	[ModifiedDate] [datetime2](7) NULL,
	[ModifiedBy] [int] NULL,
	[DeletedDate] [datetime2](7) NULL,
	[DeletedBy] [int] NULL,
 CONSTRAINT [PK_app_TrainingUpdates] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
END
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[app].[SupportLogs]') AND type in (N'U'))
BEGIN
CREATE TABLE [app].[SupportLogs](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[ClientCode] [nvarchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[LogDate] [nvarchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ModuleName] [nvarchar](120) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SubModule] [nvarchar](120) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Problem] [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Solution] [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Status] [nvarchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[Emailed] [bit] NOT NULL,
	[Tasked] [bit] NOT NULL,
	[IsDeletedTransaction] [bit] NOT NULL,
	[CreatedDate] [datetime2](7) NULL,
	[CreatedBy] [int] NULL,
	[ModifiedDate] [datetime2](7) NULL,
	[ModifiedBy] [int] NULL,
	[DeletedDate] [datetime2](7) NULL,
	[DeletedBy] [int] NULL,
 CONSTRAINT [PK_app_SupportLogs] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
END
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[Users]') AND type in (N'U'))
BEGIN
CREATE TABLE [dbo].[Users](
	[UserID] [int] IDENTITY(1,1) NOT NULL,
	[FullName] [nvarchar](100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Email] [nvarchar](100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PasswordHash] [nvarchar](256) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Role] [nvarchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[IsActive] [bit] NULL,
	[DateCreated] [datetime] NULL,
	[EmailVerified] [bit] NULL,
	[EmailToken] [nvarchar](100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ResetToken] [nvarchar](100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[TokenExpiry] [datetime] NULL,
	[WhatsAppNumber] [nvarchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[EmployeeCode] [nvarchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
 CONSTRAINT [PK__Users__1788CCACF66CF2C2] PRIMARY KEY CLUSTERED 
(
	[UserID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [UQ__Users__A9D105347978BB30] UNIQUE NONCLUSTERED 
(
	[Email] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
END
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[app].[Users]') AND type in (N'U'))
BEGIN
CREATE TABLE [app].[Users](
	[UserId] [int] IDENTITY(1,1) NOT NULL,
	[FullName] [nvarchar](120) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[Email] [nvarchar](150) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[PasswordHash] [nvarchar](256) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[Role] [nvarchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[ReportingManagerId] [int] NULL,
	[IsActive] [bit] NOT NULL,
	[CreatedAt] [datetime2](7) NOT NULL,
	[CompanyId] [int] NOT NULL,
	[ProductionUnitId] [bigint] NOT NULL,
	[FYear] [nvarchar](16) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[CompanyUsername] [nvarchar](80) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CompanyPassword] [nvarchar](80) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SmtpUsername] [nvarchar](200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SmtpPassword] [nvarchar](200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SmtpServer] [nvarchar](200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SmtpPort] [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SmtpAuthenticate] [bit] NULL,
	[SmtpUseSSL] [bit] NULL,
	[EmailProvider] [nvarchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[EmployeeID] [int] NULL,
	[EmployeeCode] [nvarchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Mobile] [nvarchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PersonalEmail] [nvarchar](200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DateOfBirth] [datetime2](7) NULL,
	[Gender] [nvarchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[BloodGroup] [nvarchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[MaritalStatus] [nvarchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[WeddingDate] [datetime2](7) NULL,
	[CurrentAddress] [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PermanentAddress] [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DateOfJoining] [datetime2](7) NULL,
	[ConfirmationDate] [datetime2](7) NULL,
	[EmployeeType] [nvarchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[WorkLocation] [nvarchar](100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[UanNumber] [nvarchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PanCardNumber] [nvarchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[AadharCardNumber] [nvarchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Status] [nvarchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[IsLoginEnabled] [bit] NULL,
	[PhotoPath] [nvarchar](500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DepartmentID] [int] NULL,
	[DesignationID] [int] NULL,
	[FatherName] [nvarchar](200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[EmergencyContactNumber] [nvarchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[EmergencyContactRelation] [nvarchar](100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CanProcureAssets] [bit] NULL,
	[BiometricCode] [nvarchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[IsDeletedTransaction] [bit] NOT NULL,
	[EmailSignature] [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CreatedDate] [datetime2](7) NULL,
	[CreatedBy] [int] NULL,
	[ModifiedDate] [datetime2](7) NULL,
	[ModifiedBy] [int] NULL,
	[DeletedDate] [datetime2](7) NULL,
	[DeletedBy] [int] NULL,
	[LastSeenAt] [datetime2](7) NULL,
	[NotifyMessages] [bit] NOT NULL,
	[NotifyEmails] [bit] NOT NULL,
	[LastEmailNotifiedAt] [datetime2](7) NULL,
 CONSTRAINT [PK_app_Users] PRIMARY KEY CLUSTERED 
(
	[UserId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
END
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[app].[UserProjectAssignment]') AND type in (N'U'))
BEGIN
CREATE TABLE [app].[UserProjectAssignment](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[UserID] [bigint] NOT NULL,
	[ProjectCode] [nvarchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[ProjectName] [nvarchar](300) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ApplicationName] [nvarchar](100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CompanyID] [int] NULL,
	[AssignedBy] [bigint] NULL,
	[AssignedAt] [datetime2](7) NOT NULL,
	[IsDeletedTransaction] [bit] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
END
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[UserPagePermissions]') AND type in (N'U'))
BEGIN
CREATE TABLE [dbo].[UserPagePermissions](
	[PermissionID] [int] IDENTITY(1,1) NOT NULL,
	[UserID] [int] NOT NULL,
	[PageName] [varchar](100) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[PermissionID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
END
GO
SET ANSI_PADDING OFF
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[Tickets]') AND type in (N'U'))
BEGIN
CREATE TABLE [dbo].[Tickets](
	[TicketID] [int] IDENTITY(1,1) NOT NULL,
	[TicketNo] [nvarchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[AssignedToID] [int] NOT NULL,
	[CreatedByID] [int] NOT NULL,
	[Department] [nvarchar](100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DateCreated] [datetime] NOT NULL,
	[Status] [nvarchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[Summary] [nvarchar](500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Description] [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ExpectedCompletionDate] [datetime] NULL,
PRIMARY KEY CLUSTERED 
(
	[TicketID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
UNIQUE NONCLUSTERED 
(
	[TicketNo] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
END
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[PointTimeLog]') AND type in (N'U'))
BEGIN
CREATE TABLE [dbo].[PointTimeLog](
	[LogID] [int] IDENTITY(1,1) NOT NULL,
	[PointID] [int] NOT NULL,
	[Action] [nvarchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[ActionTime] [datetime] NULL,
	[PerformedByID] [int] NULL,
	[Remarks] [nvarchar](500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
PRIMARY KEY CLUSTERED 
(
	[LogID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
END
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[Points]') AND type in (N'U'))
BEGIN
CREATE TABLE [dbo].[Points](
	[PointID] [int] IDENTITY(1,1) NOT NULL,
	[Title] [nvarchar](250) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[Summary] [nvarchar](500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Description] [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[CustomerID] [int] NOT NULL,
	[ProductID] [int] NOT NULL,
	[ReportedByID] [int] NOT NULL,
	[AssignedToID] [int] NULL,
	[DateCreated] [datetime] NOT NULL,
	[StartDate] [datetime] NULL,
	[DateCompleted] [datetime] NULL,
	[DateClosed] [datetime] NULL,
	[Status] [nvarchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[Priority] [nvarchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[Category] [nvarchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[Complexity] [nvarchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[TicketID] [int] NULL,
	[ExpectedDate] [datetime] NULL,
	[DateSentToQC] [datetime] NULL,
	[TesterStartDate] [datetime] NULL,
	[DeveloperRemark] [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[TesterRemark] [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[TesterCompleteDate] [datetime] NULL,
	[SortOrder] [int] NULL,
	[IsVerified] [bit] NOT NULL,
	[IsDeadlineNotified] [bit] NOT NULL,
	[ExpectedMinutes] [int] NULL,
	[TotalTimeSpent] [int] NULL,
	[PauseTimeMinutes] [int] NULL,
	[LastActionTime] [datetime] NULL,
	[SupportStartDate] [datetime] NULL,
	[SupportCompleteDate] [datetime] NULL,
	[SupportTimeSpent] [int] NULL,
	[SupportPauseTime] [int] NULL,
	[SupportLastActionTime] [datetime] NULL,
	[IsSupportPaused] [bit] NULL,
	[SupportRemark] [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[IsDeveloperPaused] [bit] NOT NULL,
	[VerificationStatus] [int] NOT NULL,
	[ToDoDate] [date] NULL,
	[MergeAssignedToID] [int] NULL,
	[DateSentToMerge] [datetime] NULL,
	[DateSupportVerified] [datetime] NULL,
	[DateTicketVerified] [datetime] NULL,
	[AdminRemark] [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Module] [nvarchar](200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SubModule] [nvarchar](200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
PRIMARY KEY CLUSTERED 
(
	[PointID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
END
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[PointHistory]') AND type in (N'U'))
BEGIN
CREATE TABLE [dbo].[PointHistory](
	[HistoryID] [int] IDENTITY(1,1) NOT NULL,
	[PointID] [int] NOT NULL,
	[DeveloperID] [int] NULL,
	[TesterID] [int] NULL,
	[StartDate] [datetime] NULL,
	[CompleteDate] [datetime] NULL,
	[SentToQCDate] [datetime] NULL,
	[TesterStartDate] [datetime] NULL,
	[FinalStatusDate] [datetime] NULL,
	[DeveloperRemark] [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[TesterRemark] [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CycleStatus] [nvarchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[TesterCompleteDate] [datetime] NULL,
	[TimeSpentMinutes] [int] NULL,
	[ExpectedMinutes] [int] NULL,
	[ExtraTimeMinutes] [int] NULL,
	[SupportID] [int] NULL,
	[SupportStartDate] [datetime] NULL,
	[SupportCompleteDate] [datetime] NULL,
	[SupportTimeSpentMinutes] [int] NULL,
	[SupportRemark] [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SupportSentToQCDate] [datetime] NULL,
	[SupportPauseMinutes] [int] NULL,
	[DeveloperPauseMinutes] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[HistoryID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
END
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[PointAttachments]') AND type in (N'U'))
BEGIN
CREATE TABLE [dbo].[PointAttachments](
	[AttachmentID] [int] IDENTITY(1,1) NOT NULL,
	[PointID] [int] NOT NULL,
	[FileName] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[FilePath] [nvarchar](500) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[UploadedByID] [int] NOT NULL,
	[UploadTimestamp] [datetime] NOT NULL,
	[HistoryID] [int] NULL,
	[OriginalFileName] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[IsDeletedTransaction] [bit] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[AttachmentID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
END
GO
IF NOT EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[app].[Notifications]') AND name = N'IX_Notifications_User')
CREATE NONCLUSTERED INDEX [IX_Notifications_User] ON [app].[Notifications]
(
	[UserID] ASC,
	[IsRead] ASC,
	[CreatedAt] DESC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
SET ANSI_PADDING ON

GO
IF NOT EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[app].[Employees]') AND name = N'UX_app_Employees_BiometricCode')
CREATE UNIQUE NONCLUSTERED INDEX [UX_app_Employees_BiometricCode] ON [app].[Employees]
(
	[BiometricCode] ASC
)
WHERE ([BiometricCode] IS NOT NULL)
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
SET ANSI_PADDING ON

GO
IF NOT EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[app].[Employees]') AND name = N'UX_app_Employees_EmployeeCode')
CREATE UNIQUE NONCLUSTERED INDEX [UX_app_Employees_EmployeeCode] ON [app].[Employees]
(
	[EmployeeCode] ASC
)
WHERE ([EmployeeCode] IS NOT NULL)
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
IF NOT EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[app].[EmailTemplateAttachments]') AND name = N'IX_ETA_TemplateId')
CREATE NONCLUSTERED INDEX [IX_ETA_TemplateId] ON [app].[EmailTemplateAttachments]
(
	[TemplateId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
SET ANSI_PADDING ON

GO
IF NOT EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[app].[EmailHistory]') AND name = N'IX_EmailHistory_Client')
CREATE NONCLUSTERED INDEX [IX_EmailHistory_Client] ON [app].[EmailHistory]
(
	[ClientCode] ASC,
	[SentAt] DESC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
IF NOT EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[app].[EmailHistory]') AND name = N'IX_EmailHistory_Point')
CREATE NONCLUSTERED INDEX [IX_EmailHistory_Point] ON [app].[EmailHistory]
(
	[PointId] ASC,
	[SentAt] DESC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
IF NOT EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[app].[ChatMessages]') AND name = N'IX_ChatMessages_Parent')
CREATE NONCLUSTERED INDEX [IX_ChatMessages_Parent] ON [app].[ChatMessages]
(
	[ParentMessageID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
IF NOT EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[app].[ChatMessages]') AND name = N'IX_ChatMessages_Room')
CREATE NONCLUSTERED INDEX [IX_ChatMessages_Room] ON [app].[ChatMessages]
(
	[CompanyID] ASC,
	[RoomID] ASC,
	[CreatedAt] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
IF NOT EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[app].[UserProjectAssignment]') AND name = N'IX_UPA_UserID')
CREATE NONCLUSTERED INDEX [IX_UPA_UserID] ON [app].[UserProjectAssignment]
(
	[UserID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
IF NOT EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[dbo].[PointTimeLog]') AND name = N'IX_PointTimeLog_ActionTime')
CREATE NONCLUSTERED INDEX [IX_PointTimeLog_ActionTime] ON [dbo].[PointTimeLog]
(
	[ActionTime] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
IF NOT EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[dbo].[PointTimeLog]') AND name = N'IX_PointTimeLog_PointID')
CREATE NONCLUSTERED INDEX [IX_PointTimeLog_PointID] ON [dbo].[PointTimeLog]
(
	[PointID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[app].[DF_OnsiteVisits_IsDelTxn]') AND type = 'D')
BEGIN
ALTER TABLE [app].[OnsiteVisits] ADD  CONSTRAINT [DF_OnsiteVisits_IsDelTxn]  DEFAULT ((0)) FOR [IsDeletedTransaction]
END

GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[app].[DF_OnsiteVisits_CreatedDate]') AND type = 'D')
BEGIN
ALTER TABLE [app].[OnsiteVisits] ADD  CONSTRAINT [DF_OnsiteVisits_CreatedDate]  DEFAULT (sysdatetime()) FOR [CreatedDate]
END

GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[DF_Notifications_IsRead]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[Notifications] ADD  CONSTRAINT [DF_Notifications_IsRead]  DEFAULT ((0)) FOR [IsRead]
END

GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[DF_Notifications_DateCreated]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[Notifications] ADD  CONSTRAINT [DF_Notifications_DateCreated]  DEFAULT (getdate()) FOR [DateCreated]
END

GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[app].[DF_Notif_Company]') AND type = 'D')
BEGIN
ALTER TABLE [app].[Notifications] ADD  CONSTRAINT [DF_Notif_Company]  DEFAULT ((1)) FOR [CompanyID]
END

GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[app].[DF_Notif_Type]') AND type = 'D')
BEGIN
ALTER TABLE [app].[Notifications] ADD  CONSTRAINT [DF_Notif_Type]  DEFAULT ('Message') FOR [Type]
END

GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[app].[DF_Notif_Read]') AND type = 'D')
BEGIN
ALTER TABLE [app].[Notifications] ADD  CONSTRAINT [DF_Notif_Read]  DEFAULT ((0)) FOR [IsRead]
END

GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[app].[DF_Notif_At]') AND type = 'D')
BEGIN
ALTER TABLE [app].[Notifications] ADD  CONSTRAINT [DF_Notif_At]  DEFAULT (sysutcdatetime()) FOR [CreatedAt]
END

GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[app].[DF_MM_IsSidebarItem]') AND type = 'D')
BEGIN
ALTER TABLE [app].[ModuleMaster] ADD  CONSTRAINT [DF_MM_IsSidebarItem]  DEFAULT ((1)) FOR [IsSidebarItem]
END

GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[app].[DF__ModuleGro__Modul__2EA5EC27]') AND type = 'D')
BEGIN
ALTER TABLE [app].[ModuleGroupDeletionLog] ADD  DEFAULT ((0)) FOR [ModulesDeleted]
END

GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[app].[DF__ModuleGro__Delet__2F9A1060]') AND type = 'D')
BEGIN
ALTER TABLE [app].[ModuleGroupDeletionLog] ADD  DEFAULT (sysdatetime()) FOR [DeletedAt]
END

GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[app].[DF_Milestones_IsDelTxn]') AND type = 'D')
BEGIN
ALTER TABLE [app].[Milestones] ADD  CONSTRAINT [DF_Milestones_IsDelTxn]  DEFAULT ((0)) FOR [IsDeletedTransaction]
END

GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[app].[DF_Milestones_CreatedDate]') AND type = 'D')
BEGIN
ALTER TABLE [app].[Milestones] ADD  CONSTRAINT [DF_Milestones_CreatedDate]  DEFAULT (sysdatetime()) FOR [CreatedDate]
END

GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[app].[DF_app_Employees_CanProcureAssets]') AND type = 'D')
BEGIN
ALTER TABLE [app].[Employees] ADD  CONSTRAINT [DF_app_Employees_CanProcureAssets]  DEFAULT ((0)) FOR [CanProcureAssets]
END

GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[app].[DF_EmailTemplates_Subject]') AND type = 'D')
BEGIN
ALTER TABLE [app].[EmailTemplates] ADD  CONSTRAINT [DF_EmailTemplates_Subject]  DEFAULT ('') FOR [Subject]
END

GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[app].[DF_EmailTemplates_Body]') AND type = 'D')
BEGIN
ALTER TABLE [app].[EmailTemplates] ADD  CONSTRAINT [DF_EmailTemplates_Body]  DEFAULT ('') FOR [Body]
END

GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[app].[DF_EmailTemplates_IsActive]') AND type = 'D')
BEGIN
ALTER TABLE [app].[EmailTemplates] ADD  CONSTRAINT [DF_EmailTemplates_IsActive]  DEFAULT ((1)) FOR [IsActive]
END

GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[app].[DF_EmailTemplates_Created]') AND type = 'D')
BEGIN
ALTER TABLE [app].[EmailTemplates] ADD  CONSTRAINT [DF_EmailTemplates_Created]  DEFAULT (sysutcdatetime()) FOR [CreatedAt]
END

GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[app].[DF_EmailTemplates_Updated]') AND type = 'D')
BEGIN
ALTER TABLE [app].[EmailTemplates] ADD  CONSTRAINT [DF_EmailTemplates_Updated]  DEFAULT (sysutcdatetime()) FOR [UpdatedAt]
END

GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[app].[DF_EmailTemplates_IsDelTxn]') AND type = 'D')
BEGIN
ALTER TABLE [app].[EmailTemplates] ADD  CONSTRAINT [DF_EmailTemplates_IsDelTxn]  DEFAULT ((0)) FOR [IsDeletedTransaction]
END

GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[app].[DF_EmailTemplates_CreatedDate]') AND type = 'D')
BEGIN
ALTER TABLE [app].[EmailTemplates] ADD  CONSTRAINT [DF_EmailTemplates_CreatedDate]  DEFAULT (sysdatetime()) FOR [CreatedDate]
END

GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[app].[DF__EmailTemp__Creat__756D6ECB]') AND type = 'D')
BEGIN
ALTER TABLE [app].[EmailTemplateAttachments] ADD  DEFAULT (sysutcdatetime()) FOR [CreatedAt]
END

GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[app].[DF__EmailHist__SentA__55009F39]') AND type = 'D')
BEGIN
ALTER TABLE [app].[EmailHistory] ADD  DEFAULT (getdate()) FOR [SentAt]
END

GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[DF__Customers__IsAct__32E0915F]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[Customers] ADD  DEFAULT ((1)) FOR [IsActive]
END

GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[DF__Customers__DateC__33D4B598]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[Customers] ADD  DEFAULT (getdate()) FOR [DateCreated]
END

GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[app].[DF_Clients_CreatedDate]') AND type = 'D')
BEGIN
ALTER TABLE [app].[Clients] ADD  CONSTRAINT [DF_Clients_CreatedDate]  DEFAULT (sysdatetime()) FOR [CreatedDate]
END

GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[app].[DF_ClientDocuments_SavedAt]') AND type = 'D')
BEGIN
ALTER TABLE [app].[ClientDocuments] ADD  CONSTRAINT [DF_ClientDocuments_SavedAt]  DEFAULT (sysdatetime()) FOR [SavedAt]
END

GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[app].[DF_ClientDocuments_CreatedDate]') AND type = 'D')
BEGIN
ALTER TABLE [app].[ClientDocuments] ADD  CONSTRAINT [DF_ClientDocuments_CreatedDate]  DEFAULT (sysdatetime()) FOR [CreatedDate]
END

GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[app].[DF__ChatRooms__IsPub__16CE6296]') AND type = 'D')
BEGIN
ALTER TABLE [app].[ChatRooms] ADD  DEFAULT ((0)) FOR [IsPublic]
END

GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[app].[DF__ChatRooms__IsRea__17C286CF]') AND type = 'D')
BEGIN
ALTER TABLE [app].[ChatRooms] ADD  DEFAULT ((0)) FOR [IsReadOnly]
END

GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[app].[DF__ChatRooms__Creat__18B6AB08]') AND type = 'D')
BEGIN
ALTER TABLE [app].[ChatRooms] ADD  DEFAULT (sysutcdatetime()) FOR [CreatedDate]
END

GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[app].[DF__ChatRooms__Updat__19AACF41]') AND type = 'D')
BEGIN
ALTER TABLE [app].[ChatRooms] ADD  DEFAULT (sysutcdatetime()) FOR [UpdatedDate]
END

GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[app].[DF__ChatRooms__IsArc__1A9EF37A]') AND type = 'D')
BEGIN
ALTER TABLE [app].[ChatRooms] ADD  DEFAULT ((0)) FOR [IsArchived]
END

GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[app].[DF__ChatRooms__IsDel__1B9317B3]') AND type = 'D')
BEGIN
ALTER TABLE [app].[ChatRooms] ADD  DEFAULT ((0)) FOR [IsDeleted]
END

GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[app].[DF_ChatStars_Company]') AND type = 'D')
BEGIN
ALTER TABLE [app].[ChatMessageStars] ADD  CONSTRAINT [DF_ChatStars_Company]  DEFAULT ((1)) FOR [CompanyID]
END

GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[app].[DF_ChatStars_At]') AND type = 'D')
BEGIN
ALTER TABLE [app].[ChatMessageStars] ADD  CONSTRAINT [DF_ChatStars_At]  DEFAULT (sysutcdatetime()) FOR [StarredAt]
END

GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[app].[DF__ChatMessa__Messa__1E6F845E]') AND type = 'D')
BEGIN
ALTER TABLE [app].[ChatMessages] ADD  DEFAULT ('Text') FOR [MessageType]
END

GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[app].[DF__ChatMessa__Reply__1F63A897]') AND type = 'D')
BEGIN
ALTER TABLE [app].[ChatMessages] ADD  DEFAULT ((0)) FOR [ReplyDepth]
END

GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[app].[DF__ChatMessa__Reply__2057CCD0]') AND type = 'D')
BEGIN
ALTER TABLE [app].[ChatMessages] ADD  DEFAULT ((0)) FOR [ReplyCount]
END

GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[app].[DF__ChatMessa__Creat__214BF109]') AND type = 'D')
BEGIN
ALTER TABLE [app].[ChatMessages] ADD  DEFAULT (sysutcdatetime()) FOR [CreatedAt]
END

GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[app].[DF__ChatMessa__IsEdi__22401542]') AND type = 'D')
BEGIN
ALTER TABLE [app].[ChatMessages] ADD  DEFAULT ((0)) FOR [IsEdited]
END

GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[app].[DF__ChatMessa__IsDel__2334397B]') AND type = 'D')
BEGIN
ALTER TABLE [app].[ChatMessages] ADD  DEFAULT ((0)) FOR [IsDeleted]
END

GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[app].[DF_ChatMessages_IsPinned]') AND type = 'D')
BEGIN
ALTER TABLE [app].[ChatMessages] ADD  CONSTRAINT [DF_ChatMessages_IsPinned]  DEFAULT ((0)) FOR [IsPinned]
END

GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[app].[DF_ChatHidden_Company]') AND type = 'D')
BEGIN
ALTER TABLE [app].[ChatMessageHidden] ADD  CONSTRAINT [DF_ChatHidden_Company]  DEFAULT ((1)) FOR [CompanyID]
END

GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[app].[DF_ChatHidden_At]') AND type = 'D')
BEGIN
ALTER TABLE [app].[ChatMessageHidden] ADD  CONSTRAINT [DF_ChatHidden_At]  DEFAULT (sysutcdatetime()) FOR [HiddenAt]
END

GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[app].[DF_ChangeRequests_IsDelTxn]') AND type = 'D')
BEGIN
ALTER TABLE [app].[ChangeRequests] ADD  CONSTRAINT [DF_ChangeRequests_IsDelTxn]  DEFAULT ((0)) FOR [IsDeletedTransaction]
END

GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[app].[DF_ChangeRequests_Pointed]') AND type = 'D')
BEGIN
ALTER TABLE [app].[ChangeRequests] ADD  CONSTRAINT [DF_ChangeRequests_Pointed]  DEFAULT ((0)) FOR [Pointed]
END

GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[app].[DF_ChangeRequests_CreatedDate]') AND type = 'D')
BEGIN
ALTER TABLE [app].[ChangeRequests] ADD  CONSTRAINT [DF_ChangeRequests_CreatedDate]  DEFAULT (sysdatetime()) FOR [CreatedDate]
END

GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[DF__Categorie__IsAct__160F4887]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[Categories] ADD  DEFAULT ((1)) FOR [IsActive]
END

GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[DF__Products__IsActi__37A5467C]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[Products] ADD  DEFAULT ((1)) FOR [IsActive]
END

GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[app].[DF_TrainingUpdates_IsDelTxn]') AND type = 'D')
BEGIN
ALTER TABLE [app].[TrainingUpdates] ADD  CONSTRAINT [DF_TrainingUpdates_IsDelTxn]  DEFAULT ((0)) FOR [IsDeletedTransaction]
END

GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[app].[DF_TrainingUpdates_CreatedDate]') AND type = 'D')
BEGIN
ALTER TABLE [app].[TrainingUpdates] ADD  CONSTRAINT [DF_TrainingUpdates_CreatedDate]  DEFAULT (sysdatetime()) FOR [CreatedDate]
END

GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[app].[DF_SupportLogs_IsDelTxn]') AND type = 'D')
BEGIN
ALTER TABLE [app].[SupportLogs] ADD  CONSTRAINT [DF_SupportLogs_IsDelTxn]  DEFAULT ((0)) FOR [IsDeletedTransaction]
END

GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[app].[DF_SupportLogs_CreatedDate]') AND type = 'D')
BEGIN
ALTER TABLE [app].[SupportLogs] ADD  CONSTRAINT [DF_SupportLogs_CreatedDate]  DEFAULT (sysdatetime()) FOR [CreatedDate]
END

GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[DF__Users__IsActive__3A81B327]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[Users] ADD  CONSTRAINT [DF__Users__IsActive__3A81B327]  DEFAULT ((1)) FOR [IsActive]
END

GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[DF__Users__DateCreat__3B75D760]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[Users] ADD  CONSTRAINT [DF__Users__DateCreat__3B75D760]  DEFAULT (getdate()) FOR [DateCreated]
END

GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[DF__Users__EmailVeri__3C69FB99]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[Users] ADD  CONSTRAINT [DF__Users__EmailVeri__3C69FB99]  DEFAULT ((0)) FOR [EmailVerified]
END

GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[app].[DF_Users_IsDelTxn]') AND type = 'D')
BEGIN
ALTER TABLE [app].[Users] ADD  CONSTRAINT [DF_Users_IsDelTxn]  DEFAULT ((0)) FOR [IsDeletedTransaction]
END

GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[app].[DF_Users_CreatedDate]') AND type = 'D')
BEGIN
ALTER TABLE [app].[Users] ADD  CONSTRAINT [DF_Users_CreatedDate]  DEFAULT (sysdatetime()) FOR [CreatedDate]
END

GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[app].[DF_Users_NotifyMsg]') AND type = 'D')
BEGIN
ALTER TABLE [app].[Users] ADD  CONSTRAINT [DF_Users_NotifyMsg]  DEFAULT ((1)) FOR [NotifyMessages]
END

GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[app].[DF_Users_NotifyEmail]') AND type = 'D')
BEGIN
ALTER TABLE [app].[Users] ADD  CONSTRAINT [DF_Users_NotifyEmail]  DEFAULT ((1)) FOR [NotifyEmails]
END

GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[app].[DF__UserProje__Assig__09746778]') AND type = 'D')
BEGIN
ALTER TABLE [app].[UserProjectAssignment] ADD  DEFAULT (sysutcdatetime()) FOR [AssignedAt]
END

GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[app].[DF__UserProje__IsDel__0A688BB1]') AND type = 'D')
BEGIN
ALTER TABLE [app].[UserProjectAssignment] ADD  DEFAULT ((0)) FOR [IsDeletedTransaction]
END

GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[DF__Tickets__DateCre__38996AB5]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[Tickets] ADD  DEFAULT (getdate()) FOR [DateCreated]
END

GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[DF__Tickets__Status__398D8EEE]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[Tickets] ADD  DEFAULT ('Open') FOR [Status]
END

GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[DF__PointTime__Actio__03F0984C]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[PointTimeLog] ADD  DEFAULT (getdate()) FOR [ActionTime]
END

GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[DF__Points__DateCrea__35BCFE0A]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[Points] ADD  DEFAULT (getdate()) FOR [DateCreated]
END

GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[DF__Points__Status__36B12243]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[Points] ADD  DEFAULT ('Queue') FOR [Status]
END

GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[DF_Points_IsVerified]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[Points] ADD  CONSTRAINT [DF_Points_IsVerified]  DEFAULT ((0)) FOR [IsVerified]
END

GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[DF__Points__IsDeadli__6E01572D]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[Points] ADD  DEFAULT ((0)) FOR [IsDeadlineNotified]
END

GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[DF__Points__PauseTim__01142BA1]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[Points] ADD  DEFAULT ((0)) FOR [PauseTimeMinutes]
END

GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[DF__Points__IsSuppor__0A9D95DB]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[Points] ADD  DEFAULT ((0)) FOR [IsSupportPaused]
END

GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[DF__Points__IsDevelo__0B91BA14]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[Points] ADD  DEFAULT ((0)) FOR [IsDeveloperPaused]
END

GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[DF__Points__Verifica__0C85DE4D]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[Points] ADD  DEFAULT ((0)) FOR [VerificationStatus]
END

GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[DF__PointAtta__Uploa__34C8D9D1]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[PointAttachments] ADD  DEFAULT (getdate()) FOR [UploadTimestamp]
END

GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[DF_PointAttachments_IsDelTxn]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[PointAttachments] ADD  CONSTRAINT [DF_PointAttachments_IsDelTxn]  DEFAULT ((0)) FOR [IsDeletedTransaction]
END

GO
IF NOT EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_UserPagePermissions_Users]') AND parent_object_id = OBJECT_ID(N'[dbo].[UserPagePermissions]'))
ALTER TABLE [dbo].[UserPagePermissions]  WITH CHECK ADD  CONSTRAINT [FK_UserPagePermissions_Users] FOREIGN KEY([UserID])
REFERENCES [dbo].[Users] ([UserID])
ON DELETE CASCADE
GO
IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_UserPagePermissions_Users]') AND parent_object_id = OBJECT_ID(N'[dbo].[UserPagePermissions]'))
ALTER TABLE [dbo].[UserPagePermissions] CHECK CONSTRAINT [FK_UserPagePermissions_Users]
GO
IF NOT EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_Tickets_AssignedTo]') AND parent_object_id = OBJECT_ID(N'[dbo].[Tickets]'))
ALTER TABLE [dbo].[Tickets]  WITH CHECK ADD  CONSTRAINT [FK_Tickets_AssignedTo] FOREIGN KEY([AssignedToID])
REFERENCES [dbo].[Users] ([UserID])
GO
IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_Tickets_AssignedTo]') AND parent_object_id = OBJECT_ID(N'[dbo].[Tickets]'))
ALTER TABLE [dbo].[Tickets] CHECK CONSTRAINT [FK_Tickets_AssignedTo]
GO
IF NOT EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_Tickets_CreatedBy]') AND parent_object_id = OBJECT_ID(N'[dbo].[Tickets]'))
ALTER TABLE [dbo].[Tickets]  WITH CHECK ADD  CONSTRAINT [FK_Tickets_CreatedBy] FOREIGN KEY([CreatedByID])
REFERENCES [dbo].[Users] ([UserID])
GO
IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_Tickets_CreatedBy]') AND parent_object_id = OBJECT_ID(N'[dbo].[Tickets]'))
ALTER TABLE [dbo].[Tickets] CHECK CONSTRAINT [FK_Tickets_CreatedBy]
GO
IF NOT EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK__PointTime__Perfo__05D8E0BE]') AND parent_object_id = OBJECT_ID(N'[dbo].[PointTimeLog]'))
ALTER TABLE [dbo].[PointTimeLog]  WITH CHECK ADD FOREIGN KEY([PerformedByID])
REFERENCES [dbo].[Users] ([UserID])
GO
IF NOT EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK__PointTime__Point__04E4BC85]') AND parent_object_id = OBJECT_ID(N'[dbo].[PointTimeLog]'))
ALTER TABLE [dbo].[PointTimeLog]  WITH CHECK ADD FOREIGN KEY([PointID])
REFERENCES [dbo].[Points] ([PointID])
ON DELETE CASCADE
GO
IF NOT EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_Points_AssignedTo]') AND parent_object_id = OBJECT_ID(N'[dbo].[Points]'))
ALTER TABLE [dbo].[Points]  WITH CHECK ADD  CONSTRAINT [FK_Points_AssignedTo] FOREIGN KEY([AssignedToID])
REFERENCES [dbo].[Users] ([UserID])
GO
IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_Points_AssignedTo]') AND parent_object_id = OBJECT_ID(N'[dbo].[Points]'))
ALTER TABLE [dbo].[Points] CHECK CONSTRAINT [FK_Points_AssignedTo]
GO
IF NOT EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_Points_Customers]') AND parent_object_id = OBJECT_ID(N'[dbo].[Points]'))
ALTER TABLE [dbo].[Points]  WITH CHECK ADD  CONSTRAINT [FK_Points_Customers] FOREIGN KEY([CustomerID])
REFERENCES [dbo].[Customers] ([CustomerID])
GO
IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_Points_Customers]') AND parent_object_id = OBJECT_ID(N'[dbo].[Points]'))
ALTER TABLE [dbo].[Points] CHECK CONSTRAINT [FK_Points_Customers]
GO
IF NOT EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_Points_Products]') AND parent_object_id = OBJECT_ID(N'[dbo].[Points]'))
ALTER TABLE [dbo].[Points]  WITH CHECK ADD  CONSTRAINT [FK_Points_Products] FOREIGN KEY([ProductID])
REFERENCES [dbo].[Products] ([ProductID])
GO
IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_Points_Products]') AND parent_object_id = OBJECT_ID(N'[dbo].[Points]'))
ALTER TABLE [dbo].[Points] CHECK CONSTRAINT [FK_Points_Products]
GO
IF NOT EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_Points_ReportedBy]') AND parent_object_id = OBJECT_ID(N'[dbo].[Points]'))
ALTER TABLE [dbo].[Points]  WITH CHECK ADD  CONSTRAINT [FK_Points_ReportedBy] FOREIGN KEY([ReportedByID])
REFERENCES [dbo].[Users] ([UserID])
GO
IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_Points_ReportedBy]') AND parent_object_id = OBJECT_ID(N'[dbo].[Points]'))
ALTER TABLE [dbo].[Points] CHECK CONSTRAINT [FK_Points_ReportedBy]
GO
IF NOT EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_Points_Tickets]') AND parent_object_id = OBJECT_ID(N'[dbo].[Points]'))
ALTER TABLE [dbo].[Points]  WITH CHECK ADD  CONSTRAINT [FK_Points_Tickets] FOREIGN KEY([TicketID])
REFERENCES [dbo].[Tickets] ([TicketID])
GO
IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_Points_Tickets]') AND parent_object_id = OBJECT_ID(N'[dbo].[Points]'))
ALTER TABLE [dbo].[Points] CHECK CONSTRAINT [FK_Points_Tickets]
GO
IF NOT EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_PointHistory_DeveloperID]') AND parent_object_id = OBJECT_ID(N'[dbo].[PointHistory]'))
ALTER TABLE [dbo].[PointHistory]  WITH CHECK ADD  CONSTRAINT [FK_PointHistory_DeveloperID] FOREIGN KEY([DeveloperID])
REFERENCES [dbo].[Users] ([UserID])
GO
IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_PointHistory_DeveloperID]') AND parent_object_id = OBJECT_ID(N'[dbo].[PointHistory]'))
ALTER TABLE [dbo].[PointHistory] CHECK CONSTRAINT [FK_PointHistory_DeveloperID]
GO
IF NOT EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_PointHistory_PointID]') AND parent_object_id = OBJECT_ID(N'[dbo].[PointHistory]'))
ALTER TABLE [dbo].[PointHistory]  WITH CHECK ADD  CONSTRAINT [FK_PointHistory_PointID] FOREIGN KEY([PointID])
REFERENCES [dbo].[Points] ([PointID])
ON DELETE CASCADE
GO
IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_PointHistory_PointID]') AND parent_object_id = OBJECT_ID(N'[dbo].[PointHistory]'))
ALTER TABLE [dbo].[PointHistory] CHECK CONSTRAINT [FK_PointHistory_PointID]
GO
IF NOT EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_PointHistory_TesterID]') AND parent_object_id = OBJECT_ID(N'[dbo].[PointHistory]'))
ALTER TABLE [dbo].[PointHistory]  WITH CHECK ADD  CONSTRAINT [FK_PointHistory_TesterID] FOREIGN KEY([TesterID])
REFERENCES [dbo].[Users] ([UserID])
GO
IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_PointHistory_TesterID]') AND parent_object_id = OBJECT_ID(N'[dbo].[PointHistory]'))
ALTER TABLE [dbo].[PointHistory] CHECK CONSTRAINT [FK_PointHistory_TesterID]
GO
IF NOT EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_PointAttachments_HistoryID]') AND parent_object_id = OBJECT_ID(N'[dbo].[PointAttachments]'))
ALTER TABLE [dbo].[PointAttachments]  WITH CHECK ADD  CONSTRAINT [FK_PointAttachments_HistoryID] FOREIGN KEY([HistoryID])
REFERENCES [dbo].[PointHistory] ([HistoryID])
GO
IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_PointAttachments_HistoryID]') AND parent_object_id = OBJECT_ID(N'[dbo].[PointAttachments]'))
ALTER TABLE [dbo].[PointAttachments] CHECK CONSTRAINT [FK_PointAttachments_HistoryID]
GO
IF NOT EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_PointAttachments_Points]') AND parent_object_id = OBJECT_ID(N'[dbo].[PointAttachments]'))
ALTER TABLE [dbo].[PointAttachments]  WITH CHECK ADD  CONSTRAINT [FK_PointAttachments_Points] FOREIGN KEY([PointID])
REFERENCES [dbo].[Points] ([PointID])
ON DELETE CASCADE
GO
IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_PointAttachments_Points]') AND parent_object_id = OBJECT_ID(N'[dbo].[PointAttachments]'))
ALTER TABLE [dbo].[PointAttachments] CHECK CONSTRAINT [FK_PointAttachments_Points]
GO
IF NOT EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_PointAttachments_Users]') AND parent_object_id = OBJECT_ID(N'[dbo].[PointAttachments]'))
ALTER TABLE [dbo].[PointAttachments]  WITH CHECK ADD  CONSTRAINT [FK_PointAttachments_Users] FOREIGN KEY([UploadedByID])
REFERENCES [dbo].[Users] ([UserID])
GO
IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_PointAttachments_Users]') AND parent_object_id = OBJECT_ID(N'[dbo].[PointAttachments]'))
ALTER TABLE [dbo].[PointAttachments] CHECK CONSTRAINT [FK_PointAttachments_Users]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[sp_CalculatePointTotalTime]') AND type in (N'P', N'PC'))
BEGIN
EXEC dbo.sp_executesql @statement = N'CREATE PROCEDURE [dbo].[sp_CalculatePointTotalTime] AS' 
END
GO

ALTER PROCEDURE [dbo].[sp_CalculatePointTotalTime]
    @PointID INT
AS
BEGIN
    SET NOCOUNT ON;

    DECLARE @TotalMinutes INT = 0;
    DECLARE @PauseMinutes INT = 0;
    DECLARE @StartTime DATETIME;
    DECLARE @PauseStartTime DATETIME;
    DECLARE @LastAction NVARCHAR(50);
    DECLARE @CurrentTime DATETIME = GETDATE();

    -- Get all time logs for this point
    DECLARE time_cursor CURSOR FOR
        SELECT Action, ActionTime
        FROM PointTimeLog
        WHERE PointID = @PointID
        ORDER BY ActionTime;

    DECLARE @Action NVARCHAR(50), @ActionTime DATETIME;

    OPEN time_cursor;
    FETCH NEXT FROM time_cursor INTO @Action, @ActionTime;

    WHILE @@FETCH_STATUS = 0
    BEGIN
        IF @Action = 'Start' OR @Action = 'Resume'
        BEGIN
            SET @StartTime = @ActionTime;
            -- If resuming after pause, calculate pause duration
            IF @PauseStartTime IS NOT NULL
            BEGIN
                SET @PauseMinutes = @PauseMinutes + DATEDIFF(MINUTE, @PauseStartTime, @ActionTime);
                SET @PauseStartTime = NULL;
            END
        END
        ELSE IF @Action = 'Pause' AND @StartTime IS NOT NULL
        BEGIN
            SET @TotalMinutes = @TotalMinutes + DATEDIFF(MINUTE, @StartTime, @ActionTime);
            SET @PauseStartTime = @ActionTime;
            SET @StartTime = NULL;
        END
        ELSE IF @Action = 'Complete' AND @StartTime IS NOT NULL
        BEGIN
            SET @TotalMinutes = @TotalMinutes + DATEDIFF(MINUTE, @StartTime, @ActionTime);
            SET @StartTime = NULL;
        END

        FETCH NEXT FROM time_cursor INTO @Action, @ActionTime;
    END

    CLOSE time_cursor;
    DEALLOCATE time_cursor;

    -- If still in progress, add time until now
    IF @StartTime IS NOT NULL
    BEGIN
        SET @TotalMinutes = @TotalMinutes + DATEDIFF(MINUTE, @StartTime, @CurrentTime);
    END

    -- If currently paused, add pause time until now
    IF @PauseStartTime IS NOT NULL
    BEGIN
        SET @PauseMinutes = @PauseMinutes + DATEDIFF(MINUTE, @PauseStartTime, @CurrentTime);
    END

    -- Update the Points table
    UPDATE Points
    SET TotalTimeSpent = @TotalMinutes,
        PauseTimeMinutes = @PauseMinutes
    WHERE PointID = @PointID;

    SELECT @TotalMinutes AS TotalMinutes, @PauseMinutes AS PauseMinutes;
END

GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF NOT EXISTS (SELECT * FROM sys.triggers WHERE object_id = OBJECT_ID(N'[dbo].[trg_UpdateTotalTimeSpent]'))
EXEC dbo.sp_executesql @statement = N'
CREATE TRIGGER trg_UpdateTotalTimeSpent
ON PointTimeLog
AFTER INSERT, UPDATE
AS
BEGIN
    SET NOCOUNT ON;

    -- Update TotalTimeSpent for affected points
    DECLARE @PointID INT;
    SELECT @PointID = PointID FROM inserted;

    EXEC sp_CalculatePointTotalTime @PointID;
END
' 
GO
ALTER TABLE [dbo].[PointTimeLog] ENABLE TRIGGER [trg_UpdateTotalTimeSpent]
GO
